/*
 * Copyright (C) 2024 Snowflake Computing Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.polaris.service.admin.api.impl;



import io.polaris.service.admin.api.PolarisCatalogsApiService;
import io.polaris.core.admin.model.AddGrantRequest;
import io.polaris.core.admin.model.Catalog;
import io.polaris.core.admin.model.CatalogRole;
import io.polaris.core.admin.model.CatalogRoles;
import io.polaris.core.admin.model.Catalogs;
import io.polaris.core.admin.model.CreateCatalogRequest;
import io.polaris.core.admin.model.CreateCatalogRoleRequest;
import io.polaris.core.admin.model.GrantResources;
import io.polaris.core.admin.model.PrincipalRoles;
import io.polaris.core.admin.model.RevokeGrantRequest;
import io.polaris.core.admin.model.UpdateCatalogRequest;
import io.polaris.core.admin.model.UpdateCatalogRoleRequest;

import java.util.List;

import java.io.InputStream;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.SecurityContext;

/**
 * Default implementation of the PolarisCatalogsApiService. Provides default
 * implemntations for all service methods that return 501 error codes (not implemented).
 *
 * This file is automatically generated by the OpenAPI Code Generator based on configuration in the
 * pom.xml file in the module.
 *
 * DO NOT EDIT THIS FILE BY HAND - CHANGES WILL BE AUTOMATICALLY OVERWRITTEN
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaResteasyServerCodegen", date = "2024-08-09T13:06:30.549973-04:00[America/New_York]", comments = "Generator version: 7.6.0")
public class PolarisCatalogsApiServiceImpl implements PolarisCatalogsApiService {
  public Response addGrantToCatalogRole(String catalogName,String catalogRoleName,AddGrantRequest addGrantRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response createCatalog(CreateCatalogRequest createCatalogRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response createCatalogRole(String catalogName,CreateCatalogRoleRequest createCatalogRoleRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response deleteCatalog(String catalogName,Boolean cascade,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response deleteCatalogRole(String catalogName,String catalogRoleName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response getCatalog(String catalogName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response getCatalogRole(String catalogName,String catalogRoleName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response listAssigneePrincipalRolesForCatalogRole(String catalogName,String catalogRoleName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response listCatalogRoles(String catalogName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response listCatalogs(SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response listGrantsForCatalogRole(String catalogName,String catalogRoleName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response revokeGrantFromCatalogRole(String catalogName,String catalogRoleName,Boolean cascade,RevokeGrantRequest revokeGrantRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response updateCatalog(String catalogName,UpdateCatalogRequest updateCatalogRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  public Response updateCatalogRole(String catalogName,String catalogRoleName,UpdateCatalogRoleRequest updateCatalogRoleRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
}
