/*
 * Copyright (C) 2024 Snowflake Computing Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.polaris.service.catalog.api;



import io.polaris.service.types.CommitTableRequest;
import org.apache.iceberg.rest.requests.CommitTransactionRequest;
import io.polaris.service.types.CommitViewRequest;
import org.apache.iceberg.rest.requests.CreateNamespaceRequest;
import org.apache.iceberg.rest.responses.CreateNamespaceResponse;
import org.apache.iceberg.rest.requests.CreateTableRequest;
import org.apache.iceberg.rest.requests.CreateViewRequest;
import org.apache.iceberg.rest.responses.GetNamespaceResponse;
import org.apache.iceberg.rest.responses.ErrorResponse;
import org.apache.iceberg.rest.responses.ListNamespacesResponse;
import org.apache.iceberg.rest.responses.ListTablesResponse;
import org.apache.iceberg.rest.responses.LoadTableResponse;
import io.polaris.service.types.NotificationRequest;
import org.apache.iceberg.rest.requests.RegisterTableRequest;
import org.apache.iceberg.rest.requests.RenameTableRequest;
import org.apache.iceberg.rest.requests.ReportMetricsRequest;
import org.apache.iceberg.rest.requests.UpdateNamespacePropertiesRequest;
import org.apache.iceberg.rest.responses.UpdateNamespacePropertiesResponse;

import java.util.List;

import java.io.InputStream;

import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.SecurityContext;

/**
 * Service interface for implementations of the IcebergRestCatalogApiService. Provides default
 * implemntations for all service methods that return 501 error codes (not implemented).
 *
 * This file is automatically generated by the OpenAPI Code Generator based on configuration in the
 * pom.xml file in the module.
 *
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaResteasyServerCodegen", date = "2024-08-09T13:06:30.844141-04:00[America/New_York]", comments = "Generator version: 7.6.0")
public interface IcebergRestCatalogApiService {
  default Response commitTransaction(String prefix,CommitTransactionRequest commitTransactionRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response createNamespace(String prefix,CreateNamespaceRequest createNamespaceRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response createTable(String prefix,String namespace,CreateTableRequest createTableRequest,String xIcebergAccessDelegation,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response createView(String prefix,String namespace,CreateViewRequest createViewRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response dropNamespace(String prefix,String namespace,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response dropTable(String prefix,String namespace,String table,Boolean purgeRequested,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response dropView(String prefix,String namespace,String view,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response listNamespaces(String prefix,String pageToken,Integer pageSize,String parent,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response listTables(String prefix,String namespace,String pageToken,Integer pageSize,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response listViews(String prefix,String namespace,String pageToken,Integer pageSize,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response loadNamespaceMetadata(String prefix,String namespace,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response loadTable(String prefix,String namespace,String table,String xIcebergAccessDelegation,String snapshots,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response loadView(String prefix,String namespace,String view,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response namespaceExists(String prefix,String namespace,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response registerTable(String prefix,String namespace,RegisterTableRequest registerTableRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response renameTable(String prefix,RenameTableRequest renameTableRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response renameView(String prefix,RenameTableRequest renameTableRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response replaceView(String prefix,String namespace,String view,CommitViewRequest commitViewRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response reportMetrics(String prefix,String namespace,String table,ReportMetricsRequest reportMetricsRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response sendNotification(String prefix,String namespace,String table,NotificationRequest notificationRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response tableExists(String prefix,String namespace,String table,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response updateProperties(String prefix,String namespace,UpdateNamespacePropertiesRequest updateNamespacePropertiesRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response updateTable(String prefix,String namespace,String table,CommitTableRequest commitTableRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response viewExists(String prefix,String namespace,String view,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
}
