/*
 * Copyright (C) 2024 Snowflake Computing Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.polaris.service.catalog.api;

import io.polaris.service.types.CommitTableRequest;
import org.apache.iceberg.rest.requests.CommitTransactionRequest;
import io.polaris.service.types.CommitViewRequest;
import org.apache.iceberg.rest.requests.CreateNamespaceRequest;
import org.apache.iceberg.rest.responses.CreateNamespaceResponse;
import org.apache.iceberg.rest.requests.CreateTableRequest;
import org.apache.iceberg.rest.requests.CreateViewRequest;
import org.apache.iceberg.rest.responses.GetNamespaceResponse;
import org.apache.iceberg.rest.responses.ErrorResponse;
import org.apache.iceberg.rest.responses.ListNamespacesResponse;
import org.apache.iceberg.rest.responses.ListTablesResponse;
import org.apache.iceberg.rest.responses.LoadTableResponse;
import io.polaris.service.types.NotificationRequest;
import org.apache.iceberg.rest.requests.RegisterTableRequest;
import org.apache.iceberg.rest.requests.RenameTableRequest;
import org.apache.iceberg.rest.requests.ReportMetricsRequest;
import org.apache.iceberg.rest.requests.UpdateNamespacePropertiesRequest;
import org.apache.iceberg.rest.responses.UpdateNamespacePropertiesResponse;

import io.polaris.core.resource.TimedApi;

import java.util.Map;
import java.util.List;

import java.io.InputStream;

import jakarta.annotation.security.RolesAllowed;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.HEAD;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.DefaultValue;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.HeaderParam;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.FormParam;
import jakarta.ws.rs.core.Response;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.SecurityContext;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * The CatalogApi API interface
 *
 * This file is automatically generated by the OpenAPI Code Generator based on configuration in the
 * build.gradle file.
 *
 */
@Path("/api/catalog/v1/{prefix}")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaResteasyServerCodegen", date = "2024-08-09T13:06:30.844141-04:00[America/New_York]", comments = "Generator version: 7.6.0")
public class IcebergRestCatalogApi  {
  private static final Logger LOGGER = LoggerFactory.getLogger(IcebergRestCatalogApi.class);

  private final IcebergRestCatalogApiService service;

  public IcebergRestCatalogApi(IcebergRestCatalogApiService service) {
    this.service = service;
  }

  /**
   * Commit updates to multiple tables in an atomic operation
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param commitTransactionRequest Required - Commit updates to multiple tables in an atomic operation  A commit for a single table consists of a table identifier with requirements and updates. Requirements are assertions that will be validated before attempting to make and commit changes. For example, &#x60;assert-ref-snapshot-id&#x60; will check that a named ref&#39;s snapshot ID has a certain value.  Updates are changes to make to table metadata. For example, after asserting that the current main ref is at the expected snapshot, a commit may add a new child snapshot and set the ref to the new snapshot id.
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchTableException, table to load does not exist
   * @return 409 - Conflict - CommitFailedException, one or more requirements failed. The client may retry.
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 500 - An unknown server-side problem occurred; the commit state is unknown.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 502 - A gateway or proxy received an invalid response from the upstream server; the commit state is unknown.
   * @return 504 - A server-side gateway timeout occurred; the commit state is unknown.
   * @return 5XX - A server-side problem that might not be addressable on the client.
   */
  @POST
  @Path("/transactions/commit")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.commitTransaction")
  public Response commitTransaction( @PathParam("prefix") String prefix, CommitTransactionRequest commitTransactionRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "commitTransaction")
      .addKeyValue("prefix", prefix)
      .addKeyValue("commitTransactionRequest", String.valueOf(commitTransactionRequest))
      .log();

    Response ret =
      service.commitTransaction(prefix,commitTransactionRequest,securityContext);
    LOGGER.debug("Completed execution of commitTransaction API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Create a namespace, with an optional set of properties. The server might also add properties, such as `last_modified_time` etc.
   *
   * Response type {@link CreateNamespaceResponse}
   * @param prefix Required - An optional prefix in the path
   * @param createNamespaceRequest Required - 
   *
   * @return 200 - Represents a successful call to create a namespace. Returns the namespace created, as well as any properties that were stored for the namespace, including those the server might have added. Implementations are not required to support namespace properties.
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 406 - Not Acceptable / Unsupported Operation. The server does not support this operation.
   * @return 409 - Conflict - The namespace already exists
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/namespaces")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.createNamespace")
  public Response createNamespace( @PathParam("prefix") String prefix, CreateNamespaceRequest createNamespaceRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "createNamespace")
      .addKeyValue("prefix", prefix)
      .addKeyValue("createNamespaceRequest", String.valueOf(createNamespaceRequest))
      .log();

    Response ret =
      service.createNamespace(prefix,createNamespaceRequest,securityContext);
    LOGGER.debug("Completed execution of createNamespace API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Create a table or start a create transaction, like atomic CTAS.  If `stage-create` is false, the table is created immediately.  If `stage-create` is true, the table is not created, but table metadata is initialized and returned. The service should prepare as needed for a commit to the table commit endpoint to complete the create transaction. The client uses the returned metadata to begin a transaction. To commit the transaction, the client sends all create and subsequent changes to the table commit route. Changes from the table create operation include changes like AddSchemaUpdate and SetCurrentSchemaUpdate that set the initial table state.
   *
   * Response type {@link LoadTableResult}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param createTableRequest Required - 
   * @param xIcebergAccessDelegation  Optional signal to the server that the client supports delegated access via a comma-separated list of access mechanisms.  The server may choose to supply access via any or none of the requested mechanisms.  Specific properties and handling for &#x60;vended-credentials&#x60; is documented in the &#x60;LoadTableResult&#x60; schema section of this spec document.  The protocol and specification for &#x60;remote-signing&#x60; is documented in  the &#x60;s3-signer-open-api.yaml&#x60; OpenApi spec in the &#x60;aws&#x60; module. 
   *
   * @return 200 - Table metadata result after creating a table
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - The namespace specified does not exist
   * @return 409 - Conflict - The table already exists
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/namespaces/{namespace}/tables")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.createTable")
  public Response createTable( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, CreateTableRequest createTableRequest,@HeaderParam("X-Iceberg-Access-Delegation") String xIcebergAccessDelegation,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "createTable")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("createTableRequest", String.valueOf(createTableRequest))
      .log();

    Response ret =
      service.createTable(prefix,namespace,createTableRequest,xIcebergAccessDelegation,securityContext);
    LOGGER.debug("Completed execution of createTable API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Create a view in the given namespace.
   *
   * Response type {@link LoadViewResult}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param createViewRequest Required - 
   *
   * @return 200 - View metadata result when loading a view
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - The namespace specified does not exist
   * @return 409 - Conflict - The view already exists
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/namespaces/{namespace}/views")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.createView")
  public Response createView( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, CreateViewRequest createViewRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "createView")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("createViewRequest", String.valueOf(createViewRequest))
      .log();

    Response ret =
      service.createView(prefix,namespace,createViewRequest,securityContext);
    LOGGER.debug("Completed execution of createView API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Drop a namespace from the catalog. Namespace must be empty.
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - Namespace to delete does not exist.
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @DELETE
  @Path("/namespaces/{namespace}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.dropNamespace")
  public Response dropNamespace( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "dropNamespace")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .log();

    Response ret =
      service.dropNamespace(prefix,namespace,securityContext);
    LOGGER.debug("Completed execution of dropNamespace API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Remove a table from the catalog
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param table Required - A table name
   * @param purgeRequested  Whether the user requested to purge the underlying table&#39;s data and metadata
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchTableException, Table to drop does not exist
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @DELETE
  @Path("/namespaces/{namespace}/tables/{table}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.dropTable")
  public Response dropTable( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("table") String table, @DefaultValue("false") @QueryParam("purgeRequested") Boolean purgeRequested,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "dropTable")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("table", table)
      .addKeyValue("purgeRequested", purgeRequested)
      .log();

    Response ret =
      service.dropTable(prefix,namespace,table,purgeRequested,securityContext);
    LOGGER.debug("Completed execution of dropTable API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Remove a view from the catalog
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param view Required - A view name
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchViewException, view to drop does not exist
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @DELETE
  @Path("/namespaces/{namespace}/views/{view}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.dropView")
  public Response dropView( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("view") String view,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "dropView")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("view", view)
      .log();

    Response ret =
      service.dropView(prefix,namespace,view,securityContext);
    LOGGER.debug("Completed execution of dropView API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * List all namespaces at a certain level, optionally starting from a given parent namespace. If table accounting.tax.paid.info exists, using 'SELECT NAMESPACE IN accounting' would translate into `GET /namespaces?parent=accounting` and must return a namespace, [\"accounting\", \"tax\"] only. Using 'SELECT NAMESPACE IN accounting.tax' would translate into `GET /namespaces?parent=accounting%1Ftax` and must return a namespace, [\"accounting\", \"tax\", \"paid\"]. If `parent` is not provided, all top-level namespaces should be listed.
   *
   * Response type {@link ListNamespacesResponse}
   * @param prefix Required - An optional prefix in the path
   * @param pageToken  
   * @param pageSize  For servers that support pagination, this signals an upper bound of the number of results that a client will receive. For servers that do not support pagination, clients may receive results larger than the indicated &#x60;pageSize&#x60;.
   * @param parent  An optional namespace, underneath which to list namespaces. If not provided or empty, all top-level namespaces should be listed. If parent is a multipart namespace, the parts must be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   *
   * @return 200 - A list of namespaces
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - Namespace provided in the `parent` query parameter is not found.
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @GET
  @Path("/namespaces")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.listNamespaces")
  public Response listNamespaces( @PathParam("prefix") String prefix, @QueryParam("pageToken") String pageToken, @QueryParam("pageSize") Integer pageSize, @QueryParam("parent") String parent,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "listNamespaces")
      .addKeyValue("prefix", prefix)
      .addKeyValue("pageToken", pageToken)
      .addKeyValue("pageSize", pageSize)
      .addKeyValue("parent", parent)
      .log();

    Response ret =
      service.listNamespaces(prefix,pageToken,pageSize,parent,securityContext);
    LOGGER.debug("Completed execution of listNamespaces API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Return all table identifiers under this namespace
   *
   * Response type {@link ListTablesResponse}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param pageToken  
   * @param pageSize  For servers that support pagination, this signals an upper bound of the number of results that a client will receive. For servers that do not support pagination, clients may receive results larger than the indicated &#x60;pageSize&#x60;.
   *
   * @return 200 - A list of table identifiers
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - The namespace specified does not exist
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @GET
  @Path("/namespaces/{namespace}/tables")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.listTables")
  public Response listTables( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @QueryParam("pageToken") String pageToken, @QueryParam("pageSize") Integer pageSize,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "listTables")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("pageToken", pageToken)
      .addKeyValue("pageSize", pageSize)
      .log();

    Response ret =
      service.listTables(prefix,namespace,pageToken,pageSize,securityContext);
    LOGGER.debug("Completed execution of listTables API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Return all view identifiers under this namespace
   *
   * Response type {@link ListTablesResponse}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param pageToken  
   * @param pageSize  For servers that support pagination, this signals an upper bound of the number of results that a client will receive. For servers that do not support pagination, clients may receive results larger than the indicated &#x60;pageSize&#x60;.
   *
   * @return 200 - A list of table identifiers
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - The namespace specified does not exist
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @GET
  @Path("/namespaces/{namespace}/views")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.listViews")
  public Response listViews( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @QueryParam("pageToken") String pageToken, @QueryParam("pageSize") Integer pageSize,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "listViews")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("pageToken", pageToken)
      .addKeyValue("pageSize", pageSize)
      .log();

    Response ret =
      service.listViews(prefix,namespace,pageToken,pageSize,securityContext);
    LOGGER.debug("Completed execution of listViews API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Return all stored metadata properties for a given namespace
   *
   * Response type {@link GetNamespaceResponse}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   *
   * @return 200 - Returns a namespace, as well as any properties stored on the namespace if namespace properties are supported by the server.
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - Namespace not found
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @GET
  @Path("/namespaces/{namespace}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.loadNamespaceMetadata")
  public Response loadNamespaceMetadata( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "loadNamespaceMetadata")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .log();

    Response ret =
      service.loadNamespaceMetadata(prefix,namespace,securityContext);
    LOGGER.debug("Completed execution of loadNamespaceMetadata API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Load a table from the catalog.  The response contains both configuration and table metadata. The configuration, if non-empty is used as additional configuration for the table that overrides catalog configuration. For example, this configuration may change the FileIO implementation to be used for the table.  The response also contains the table's full metadata, matching the table metadata JSON file.  The catalog configuration may contain credentials that should be used for subsequent requests for the table. The configuration key \"token\" is used to pass an access token to be used as a bearer token for table requests. Otherwise, a token may be passed using a RFC 8693 token type as a configuration key. For example, \"urn:ietf:params:oauth:token-type:jwt=<JWT-token>\".
   *
   * Response type {@link LoadTableResult}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param table Required - A table name
   * @param xIcebergAccessDelegation  Optional signal to the server that the client supports delegated access via a comma-separated list of access mechanisms.  The server may choose to supply access via any or none of the requested mechanisms.  Specific properties and handling for &#x60;vended-credentials&#x60; is documented in the &#x60;LoadTableResult&#x60; schema section of this spec document.  The protocol and specification for &#x60;remote-signing&#x60; is documented in  the &#x60;s3-signer-open-api.yaml&#x60; OpenApi spec in the &#x60;aws&#x60; module. 
   * @param snapshots  The snapshots to return in the body of the metadata. Setting the value to &#x60;all&#x60; would return the full set of snapshots currently valid for the table. Setting the value to &#x60;refs&#x60; would load all snapshots referenced by branches or tags. Default if no param is provided is &#x60;all&#x60;.
   *
   * @return 200 - Table metadata result when loading a table
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchTableException, table to load does not exist
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @GET
  @Path("/namespaces/{namespace}/tables/{table}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.loadTable")
  public Response loadTable( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("table") String table,@HeaderParam("X-Iceberg-Access-Delegation") String xIcebergAccessDelegation, @QueryParam("snapshots") String snapshots,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "loadTable")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("table", table)
      .addKeyValue("snapshots", snapshots)
      .log();

    Response ret =
      service.loadTable(prefix,namespace,table,xIcebergAccessDelegation,snapshots,securityContext);
    LOGGER.debug("Completed execution of loadTable API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Load a view from the catalog.  The response contains both configuration and view metadata. The configuration, if non-empty is used as additional configuration for the view that overrides catalog configuration.  The response also contains the view's full metadata, matching the view metadata JSON file.  The catalog configuration may contain credentials that should be used for subsequent requests for the view. The configuration key \"token\" is used to pass an access token to be used as a bearer token for view requests. Otherwise, a token may be passed using a RFC 8693 token type as a configuration key. For example, \"urn:ietf:params:oauth:token-type:jwt=<JWT-token>\".
   *
   * Response type {@link LoadViewResult}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param view Required - A view name
   *
   * @return 200 - View metadata result when loading a view
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchViewException, view to load does not exist
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @GET
  @Path("/namespaces/{namespace}/views/{view}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.loadView")
  public Response loadView( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("view") String view,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "loadView")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("view", view)
      .log();

    Response ret =
      service.loadView(prefix,namespace,view,securityContext);
    LOGGER.debug("Completed execution of loadView API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Check if a namespace exists. The response does not contain a body.
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - Namespace not found
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @HEAD
  @Path("/namespaces/{namespace}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.namespaceExists")
  public Response namespaceExists( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "namespaceExists")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .log();

    Response ret =
      service.namespaceExists(prefix,namespace,securityContext);
    LOGGER.debug("Completed execution of namespaceExists API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Register a table using given metadata file location.
   *
   * Response type {@link LoadTableResult}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param registerTableRequest Required - 
   *
   * @return 200 - Table metadata result when loading a table
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - The namespace specified does not exist
   * @return 409 - Conflict - The table already exists
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/namespaces/{namespace}/register")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.registerTable")
  public Response registerTable( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, RegisterTableRequest registerTableRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "registerTable")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("registerTableRequest", String.valueOf(registerTableRequest))
      .log();

    Response ret =
      service.registerTable(prefix,namespace,registerTableRequest,securityContext);
    LOGGER.debug("Completed execution of registerTable API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Rename a table from one identifier to another. It's valid to move a table across namespaces, but the server implementation is not required to support it.
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param renameTableRequest Required - Current table identifier to rename and new table identifier to rename to
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchTableException, Table to rename does not exist - NoSuchNamespaceException, The target namespace of the new table identifier does not exist
   * @return 406 - Not Acceptable / Unsupported Operation. The server does not support this operation.
   * @return 409 - Conflict - The target identifier to rename to already exists as a table or view
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/tables/rename")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.renameTable")
  public Response renameTable( @PathParam("prefix") String prefix, RenameTableRequest renameTableRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "renameTable")
      .addKeyValue("prefix", prefix)
      .addKeyValue("renameTableRequest", String.valueOf(renameTableRequest))
      .log();

    Response ret =
      service.renameTable(prefix,renameTableRequest,securityContext);
    LOGGER.debug("Completed execution of renameTable API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Rename a view from one identifier to another. It's valid to move a view across namespaces, but the server implementation is not required to support it.
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param renameTableRequest Required - Current view identifier to rename and new view identifier to rename to
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchViewException, view to rename does not exist - NoSuchNamespaceException, The target namespace of the new identifier does not exist
   * @return 406 - Not Acceptable / Unsupported Operation. The server does not support this operation.
   * @return 409 - Conflict - The target identifier to rename to already exists as a table or view
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/views/rename")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.renameView")
  public Response renameView( @PathParam("prefix") String prefix, RenameTableRequest renameTableRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "renameView")
      .addKeyValue("prefix", prefix)
      .addKeyValue("renameTableRequest", String.valueOf(renameTableRequest))
      .log();

    Response ret =
      service.renameView(prefix,renameTableRequest,securityContext);
    LOGGER.debug("Completed execution of renameView API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Commit updates to a view.
   *
   * Response type {@link LoadViewResult}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param view Required - A view name
   * @param commitViewRequest Required - 
   *
   * @return 200 - View metadata result when loading a view
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchViewException, view to load does not exist
   * @return 409 - Conflict - CommitFailedException. The client may retry.
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 500 - An unknown server-side problem occurred; the commit state is unknown.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 502 - A gateway or proxy received an invalid response from the upstream server; the commit state is unknown.
   * @return 504 - A server-side gateway timeout occurred; the commit state is unknown.
   * @return 5XX - A server-side problem that might not be addressable on the client.
   */
  @POST
  @Path("/namespaces/{namespace}/views/{view}")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.replaceView")
  public Response replaceView( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("view") String view, CommitViewRequest commitViewRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "replaceView")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("view", view)
      .addKeyValue("commitViewRequest", String.valueOf(commitViewRequest))
      .log();

    Response ret =
      service.replaceView(prefix,namespace,view,commitViewRequest,securityContext);
    LOGGER.debug("Completed execution of replaceView API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Send a metrics report to this endpoint to be processed by the backend
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param table Required - A table name
   * @param reportMetricsRequest Required - The request containing the metrics report to be sent
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchTableException, table to load does not exist
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/namespaces/{namespace}/tables/{table}/metrics")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.reportMetrics")
  public Response reportMetrics( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("table") String table, ReportMetricsRequest reportMetricsRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "reportMetrics")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("table", table)
      .addKeyValue("reportMetricsRequest", String.valueOf(reportMetricsRequest))
      .log();

    Response ret =
      service.reportMetrics(prefix,namespace,table,reportMetricsRequest,securityContext);
    LOGGER.debug("Completed execution of reportMetrics API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Sends a notification to the table
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param table Required - A table name
   * @param notificationRequest Required - The request containing the notification to be sent
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchTableException, table to load does not exist
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/namespaces/{namespace}/tables/{table}/notifications")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.sendNotification")
  public Response sendNotification( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("table") String table, NotificationRequest notificationRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "sendNotification")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("table", table)
      .addKeyValue("notificationRequest", String.valueOf(notificationRequest))
      .log();

    Response ret =
      service.sendNotification(prefix,namespace,table,notificationRequest,securityContext);
    LOGGER.debug("Completed execution of sendNotification API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Check if a table exists within a given namespace. The response does not contain a body.
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param table Required - A table name
   *
   * @return 204 - Success, no content
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchTableException, Table not found
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @HEAD
  @Path("/namespaces/{namespace}/tables/{table}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.tableExists")
  public Response tableExists( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("table") String table,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "tableExists")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("table", table)
      .log();

    Response ret =
      service.tableExists(prefix,namespace,table,securityContext);
    LOGGER.debug("Completed execution of tableExists API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Set and/or remove properties on a namespace. The request body specifies a list of properties to remove and a map of key value pairs to update. Properties that are not in the request are not modified or removed by this call. Server implementations are not required to support namespace properties.
   *
   * Response type {@link UpdateNamespacePropertiesResponse}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param updateNamespacePropertiesRequest Required - 
   *
   * @return 200 - JSON data response for a synchronous update properties request.
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - Namespace not found
   * @return 406 - Not Acceptable / Unsupported Operation. The server does not support this operation.
   * @return 422 - Unprocessable Entity - A property key was included in both `removals` and `updates`
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @POST
  @Path("/namespaces/{namespace}/properties")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.updateProperties")
  public Response updateProperties( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, UpdateNamespacePropertiesRequest updateNamespacePropertiesRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "updateProperties")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("updateNamespacePropertiesRequest", String.valueOf(updateNamespacePropertiesRequest))
      .log();

    Response ret =
      service.updateProperties(prefix,namespace,updateNamespacePropertiesRequest,securityContext);
    LOGGER.debug("Completed execution of updateProperties API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Commit updates to a table.  Commits have two parts, requirements and updates. Requirements are assertions that will be validated before attempting to make and commit changes. For example, `assert-ref-snapshot-id` will check that a named ref's snapshot ID has a certain value.  Updates are changes to make to table metadata. For example, after asserting that the current main ref is at the expected snapshot, a commit may add a new child snapshot and set the ref to the new snapshot id.  Create table transactions that are started by createTable with `stage-create` set to true are committed using this route. Transactions should include all changes to the table, including table initialization, like AddSchemaUpdate and SetCurrentSchemaUpdate. The `assert-create` requirement is used to ensure that the table was not created concurrently.
   *
   * Response type {@link CommitTableResponse}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param table Required - A table name
   * @param commitTableRequest Required - 
   *
   * @return 200 - Response used when a table is successfully updated. The table metadata JSON is returned in the metadata field. The corresponding file location of table metadata must be returned in the metadata-location field. Clients can check whether metadata has changed by comparing metadata locations.
   * @return 400 - Indicates a bad request error. It could be caused by an unexpected request body format or other forms of request validation failure, such as invalid json. Usually serves application/json content, although in some cases simple text/plain content might be returned by the server's middleware.
   * @return 401 - Unauthorized. Authentication is required and has failed or has not yet been provided.
   * @return 403 - Forbidden. Authenticated user does not have the necessary permissions.
   * @return 404 - Not Found - NoSuchTableException, table to load does not exist
   * @return 409 - Conflict - CommitFailedException, one or more requirements failed. The client may retry.
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 500 - An unknown server-side problem occurred; the commit state is unknown.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 502 - A gateway or proxy received an invalid response from the upstream server; the commit state is unknown.
   * @return 504 - A server-side gateway timeout occurred; the commit state is unknown.
   * @return 5XX - A server-side problem that might not be addressable on the client.
   */
  @POST
  @Path("/namespaces/{namespace}/tables/{table}")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.updateTable")
  public Response updateTable( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("table") String table, CommitTableRequest commitTableRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "updateTable")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("table", table)
      .addKeyValue("commitTableRequest", String.valueOf(commitTableRequest))
      .log();

    Response ret =
      service.updateTable(prefix,namespace,table,commitTableRequest,securityContext);
    LOGGER.debug("Completed execution of updateTable API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Check if a view exists within a given namespace. This request does not return a response body.
   *
   * Response type {@link Void}
   * @param prefix Required - An optional prefix in the path
   * @param namespace Required - A namespace identifier as a single string. Multipart namespace parts should be separated by the unit separator (&#x60;0x1F&#x60;) byte.
   * @param view Required - A view name
   *
   * @return 204 - Success, no content
   * @return 400 - Bad Request
   * @return 401 - Unauthorized
   * @return 404 - Not Found
   * @return 419 - Credentials have timed out. If possible, the client should refresh credentials and retry.
   * @return 503 - The service is not ready to handle the request. The client should wait and retry.  The service may additionally send a Retry-After header to indicate when to retry.
   * @return 5XX - A server-side problem that might not be addressable from the client side. Used for server 5xx errors without more specific documentation in individual routes.
   */
  @HEAD
  @Path("/namespaces/{namespace}/views/{view}")
  @Produces({ "application/json" })
  @RolesAllowed({ "catalog" })
  @TimedApi("polaris.CatalogApi.viewExists")
  public Response viewExists( @PathParam("prefix") String prefix, @PathParam("namespace") String namespace, @PathParam("view") String view,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking CatalogApi with params")
      .addKeyValue("operation", "viewExists")
      .addKeyValue("prefix", prefix)
      .addKeyValue("namespace", namespace)
      .addKeyValue("view", view)
      .log();

    Response ret =
      service.viewExists(prefix,namespace,view,securityContext);
    LOGGER.debug("Completed execution of viewExists API with status code {}", ret.getStatus());
    return ret;
  }
}
