/*
 * Copyright (C) 2024 Snowflake Computing Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.polaris.service.admin.api;



import io.polaris.core.admin.model.CreatePrincipalRequest;
import io.polaris.core.admin.model.GrantPrincipalRoleRequest;
import io.polaris.core.admin.model.Principal;
import io.polaris.core.admin.model.PrincipalRoles;
import io.polaris.core.admin.model.PrincipalWithCredentials;
import io.polaris.core.admin.model.Principals;
import io.polaris.core.admin.model.UpdatePrincipalRequest;

import java.util.List;

import java.io.InputStream;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.SecurityContext;

/**
 * Service interface for implementations of the PolarisPrincipalsApiService. Provides default
 * implemntations for all service methods that return 501 error codes (not implemented).
 *
 * This file is automatically generated by the OpenAPI Code Generator based on configuration in the
 * pom.xml file in the module.
 *
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaResteasyServerCodegen", date = "2024-08-09T13:06:30.549973-04:00[America/New_York]", comments = "Generator version: 7.6.0")
public interface PolarisPrincipalsApiService {
  default Response assignPrincipalRole(String principalName,GrantPrincipalRoleRequest grantPrincipalRoleRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response createPrincipal(CreatePrincipalRequest createPrincipalRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response deletePrincipal(String principalName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response getPrincipal(String principalName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response listPrincipalRolesAssigned(String principalName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response listPrincipals(SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response revokePrincipalRole(String principalName,String principalRoleName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response rotateCredentials(String principalName,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
  default Response updatePrincipal(String principalName,UpdatePrincipalRequest updatePrincipalRequest,SecurityContext securityContext) {
    return Response.status(501).build(); // not implemented
  }
}
