/*
 * Copyright (C) 2024 Snowflake Computing Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.polaris.service.admin.api;

import io.polaris.core.admin.model.CreatePrincipalRequest;
import io.polaris.core.admin.model.GrantPrincipalRoleRequest;
import io.polaris.core.admin.model.Principal;
import io.polaris.core.admin.model.PrincipalRoles;
import io.polaris.core.admin.model.PrincipalWithCredentials;
import io.polaris.core.admin.model.Principals;
import io.polaris.core.admin.model.UpdatePrincipalRequest;

import io.polaris.core.resource.TimedApi;

import java.util.Map;
import java.util.List;

import java.io.InputStream;

import jakarta.annotation.security.RolesAllowed;

import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.HEAD;
import jakarta.ws.rs.PATCH;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.DefaultValue;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.HeaderParam;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.FormParam;
import jakarta.ws.rs.core.Response;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.SecurityContext;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * The principals API interface
 *
 * This file is automatically generated by the OpenAPI Code Generator based on configuration in the
 * build.gradle file.
 *
 */
@Path("/api/management/v1/principals")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaResteasyServerCodegen", date = "2024-08-09T13:06:30.549973-04:00[America/New_York]", comments = "Generator version: 7.6.0")
public class PolarisPrincipalsApi  {
  private static final Logger LOGGER = LoggerFactory.getLogger(PolarisPrincipalsApi.class);

  private final PolarisPrincipalsApiService service;

  public PolarisPrincipalsApi(PolarisPrincipalsApiService service) {
    this.service = service;
  }

  /**
   * Add a role to the principal
   *
   * Response type {@link Void}
   * @param principalName Required - The name of the target principal
   * @param grantPrincipalRoleRequest Required - The principal role to assign
   *
   * @return 201 - Successful response
   * @return 403 - The caller does not have permission to add assign a role to the principal
   * @return 404 - The catalog, the principal, or the role does not exist
   */
  @PUT
  @Path("/{principalName}/principal-roles")
  @Consumes({ "application/json" })
  @RolesAllowed({  })
  @TimedApi("polaris.principals.assignPrincipalRole")
  public Response assignPrincipalRole( @Pattern(regexp="^(?!\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\$).*$") @Size(min=1,max=256) @PathParam("principalName") String principalName, @NotNull @Valid GrantPrincipalRoleRequest grantPrincipalRoleRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "assignPrincipalRole")
      .addKeyValue("principalName", principalName)
      .addKeyValue("grantPrincipalRoleRequest", String.valueOf(grantPrincipalRoleRequest))
      .log();

    Response ret =
      service.assignPrincipalRole(principalName,grantPrincipalRoleRequest,securityContext);
    LOGGER.debug("Completed execution of assignPrincipalRole API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Create a principal
   *
   * Response type {@link PrincipalWithCredentials}
   * @param createPrincipalRequest Required - The principal to create
   *
   * @return 201 - Successful response
   * @return 403 - The caller does not have permission to add a principal
   */
  @POST
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({  })
  @TimedApi("polaris.principals.createPrincipal")
  public Response createPrincipal( @NotNull @Valid CreatePrincipalRequest createPrincipalRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "createPrincipal")
      .addKeyValue("createPrincipalRequest", String.valueOf(createPrincipalRequest))
      .log();

    Response ret =
      service.createPrincipal(createPrincipalRequest,securityContext);
    LOGGER.debug("Completed execution of createPrincipal API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Remove a principal from polaris
   *
   * Response type {@link Void}
   * @param principalName Required - The principal name
   *
   * @return 204 - Success, no content
   * @return 403 - The caller does not have permission to delete a principal
   * @return 404 - The principal does not exist
   */
  @DELETE
  @Path("/{principalName}")
  @RolesAllowed({  })
  @TimedApi("polaris.principals.deletePrincipal")
  public Response deletePrincipal( @Pattern(regexp="^(?!\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\$).*$") @Size(min=1,max=256) @PathParam("principalName") String principalName,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "deletePrincipal")
      .addKeyValue("principalName", principalName)
      .log();

    Response ret =
      service.deletePrincipal(principalName,securityContext);
    LOGGER.debug("Completed execution of deletePrincipal API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Get the principal details
   *
   * Response type {@link Principal}
   * @param principalName Required - The principal name
   *
   * @return 200 - The requested principal
   * @return 403 - The caller does not have permission to get principal details
   * @return 404 - The catalog or principal does not exist
   */
  @GET
  @Path("/{principalName}")
  @Produces({ "application/json" })
  @RolesAllowed({  })
  @TimedApi("polaris.principals.getPrincipal")
  public Response getPrincipal( @Pattern(regexp="^(?!\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\$).*$") @Size(min=1,max=256) @PathParam("principalName") String principalName,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "getPrincipal")
      .addKeyValue("principalName", principalName)
      .log();

    Response ret =
      service.getPrincipal(principalName,securityContext);
    LOGGER.debug("Completed execution of getPrincipal API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * List the roles assigned to the principal
   *
   * Response type {@link PrincipalRoles}
   * @param principalName Required - The name of the target principal
   *
   * @return 200 - List of roles assigned to this principal
   * @return 403 - The caller does not have permission to list roles
   * @return 404 - The principal or catalog does not exist
   */
  @GET
  @Path("/{principalName}/principal-roles")
  @Produces({ "application/json" })
  @RolesAllowed({  })
  @TimedApi("polaris.principals.listPrincipalRolesAssigned")
  public Response listPrincipalRolesAssigned( @Pattern(regexp="^(?!\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\$).*$") @Size(min=1,max=256) @PathParam("principalName") String principalName,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "listPrincipalRolesAssigned")
      .addKeyValue("principalName", principalName)
      .log();

    Response ret =
      service.listPrincipalRolesAssigned(principalName,securityContext);
    LOGGER.debug("Completed execution of listPrincipalRolesAssigned API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * List the principals for the current catalog
   *
   * Response type {@link Principals}
   *
   * @return 200 - List of principals for this catalog
   * @return 403 - The caller does not have permission to list catalog admins
   * @return 404 - The catalog does not exist
   */
  @GET
  @Produces({ "application/json" })
  @RolesAllowed({  })
  @TimedApi("polaris.principals.listPrincipals")
  public Response listPrincipals(@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "listPrincipals")
      .log();

    Response ret =
      service.listPrincipals(securityContext);
    LOGGER.debug("Completed execution of listPrincipals API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Remove a role from a catalog principal
   *
   * Response type {@link Void}
   * @param principalName Required - The name of the target principal
   * @param principalRoleName Required - The name of the role
   *
   * @return 204 - Success, no content
   * @return 403 - The caller does not have permission to remove a role from the principal
   * @return 404 - The catalog or principal does not exist
   */
  @DELETE
  @Path("/{principalName}/principal-roles/{principalRoleName}")
  @RolesAllowed({  })
  @TimedApi("polaris.principals.revokePrincipalRole")
  public Response revokePrincipalRole( @Pattern(regexp="^(?!\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\$).*$") @Size(min=1,max=256) @PathParam("principalName") String principalName, @Pattern(regexp="^(?!\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\$).*$") @Size(min=1,max=256) @PathParam("principalRoleName") String principalRoleName,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "revokePrincipalRole")
      .addKeyValue("principalName", principalName)
      .addKeyValue("principalRoleName", principalRoleName)
      .log();

    Response ret =
      service.revokePrincipalRole(principalName,principalRoleName,securityContext);
    LOGGER.debug("Completed execution of revokePrincipalRole API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Rotate a principal's credentials. The new credentials will be returned in the response. This is the only API, aside from createPrincipal, that returns the user's credentials. This API is *not* idempotent.
   *
   * Response type {@link PrincipalWithCredentials}
   * @param principalName Required - The user name
   *
   * @return 200 - The principal details along with the newly rotated credentials
   * @return 403 - The caller does not have permission to rotate credentials
   * @return 404 - The principal does not exist
   */
  @POST
  @Path("/{principalName}/rotate")
  @Produces({ "application/json" })
  @RolesAllowed({  })
  @TimedApi("polaris.principals.rotateCredentials")
  public Response rotateCredentials( @Pattern(regexp="^(?!\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\$).*$") @Size(min=1,max=256) @PathParam("principalName") String principalName,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "rotateCredentials")
      .addKeyValue("principalName", principalName)
      .log();

    Response ret =
      service.rotateCredentials(principalName,securityContext);
    LOGGER.debug("Completed execution of rotateCredentials API with status code {}", ret.getStatus());
    return ret;
  }
  /**
   * Update an existing principal
   *
   * Response type {@link Principal}
   * @param principalName Required - The principal name
   * @param updatePrincipalRequest Required - The principal details to use in the update
   *
   * @return 200 - The updated principal
   * @return 403 - The caller does not have permission to update principal details
   * @return 404 - The principal does not exist
   * @return 409 - The entity version doesn't match the currentEntityVersion; retry after fetching latest version
   */
  @PUT
  @Path("/{principalName}")
  @Consumes({ "application/json" })
  @Produces({ "application/json" })
  @RolesAllowed({  })
  @TimedApi("polaris.principals.updatePrincipal")
  public Response updatePrincipal( @Pattern(regexp="^(?!\\s*[s|S][y|Y][s|S][t|T][e|E][m|M]\\$).*$") @Size(min=1,max=256) @PathParam("principalName") String principalName, @NotNull @Valid UpdatePrincipalRequest updatePrincipalRequest,@Context SecurityContext securityContext) {
    LOGGER.atDebug().setMessage("Invoking principals with params")
      .addKeyValue("operation", "updatePrincipal")
      .addKeyValue("principalName", principalName)
      .addKeyValue("updatePrincipalRequest", String.valueOf(updatePrincipalRequest))
      .log();

    Response ret =
      service.updatePrincipal(principalName,updatePrincipalRequest,securityContext);
    LOGGER.debug("Completed execution of updatePrincipal API with status code {}", ret.getStatus());
    return ret;
  }
}
